### ISSUE TITLE
Trying to load my own URDF in the example world.

### ISSUE THREAD

**Issue by bl33m** [uos/radarays_gazebo_plugins#1]
Hi all,

I have modified my robot's urdf file to mount a radar, as well as the included launch file to launch the example world. 

I am able to spawn the robot fine in the example when I disable the radar in the URDF.

When I re-enable the radar I receive the following output and gazebo is not able to spawn the robot.
![image](https://github.com/uos/radarays_gazebo_plugins/assets/66042567/b881bea7-6992-4e17-bb37-f432c42dbc07)
![image](https://github.com/uos/radarays_gazebo_plugins/assets/66042567/a2f6c764-ebd3-4227-8a34-eb37fc082859)
![image](https://github.com/uos/radarays_gazebo_plugins/assets/66042567/d4de9ab7-7fc1-4b52-90ec-239f0b131fd3)
![image](https://github.com/uos/radarays_gazebo_plugins/assets/66042567/757903ff-f671-481e-a306-c2c2f1c93f03)

Thanks for all the support thus far!

**Comment by amock** [comment]
If I'm not mistaken, the last commit fixed some of your issues. Therefore, this issue is probably outdated. If I'm wrong, please feel free to reopen it.
